### ISSUE TITLE
Is this means not support to use "dnode" modules?

### ISSUE THREAD

**Issue by wcc21320** [jaredallard/nexe#130]
It works in command "node app.js"; but after I build it in nexe, it block at
```js
nexe.js:105
    d.connect({host:aplan_rados_server.host, port: aplan_rados_server.port}, f
      ^
TypeError: Object #<Object> has no method 'connect'
    at Object.exports.init (nexe.js:105:7)
    at checkServer (nexe.js:56:12)
    at Array.call./home/wcc/run_test/IT/app.js.fs [as 0] (nexe.js:66:1)
    at initModule (nexe.js:29:11)
    at Array.forEach (native)
    at nexe.js:39:8
    at nexe.js:46:4
    at NativeModule.compile (node.js:900:5)
    at Function.NativeModule.require (node.js:869:18)
    at Function.Module._load (module.js:297:25)
```
I simple the project as below:
app.js:
```js
//--------------------------------------------------------
var client = require('aplan-rados-client');
var conf = {'ver':'0.1',
        'server':{host:'192.168.22.3',port:6004}
    };
function checkServer(callback){
    client.init(conf.server, function(err, inf){
        if (inf ) {
            return callback(null, inf.result);
        } else {
            console.log('radosClient init failed:', err);
            return callback(2);
        }
    });
}

checkServer(function(err, conn){
    if (err) {
        console.log('Can not contact to radosServer.');
    } else {
        console.log('radosServer ready!');
    }
});
//--------------------------------------------------------
```
and 'aplan-rados-client' has its app.js:
```js
//--------------------------------------------------------
var dnode = require('dnode');
function newDnode(){
    return dnode(undefined, {weak:false});
}

var net = require('net');
// ---------- Variables ----------
var aplan_rados_server = {
    host: '192.168.22.3',
    port: 5004
};
// ---------- Export Functions ----------
exports.init = function (options, callback) {

    if (options.host) aplan_rados_server.host = options.host;
    if (options.port) aplan_rados_server.port = options.port;

    // check server alive:
    var d = newDnode();
    d.connect({host:aplan_rados_server.host, port: aplan_rados_server.port}, function(remote, conn){
        console.log('connected to server:', options);

        remote._ping(function (s) {
            console.log('Server say: ', s);
            callback(null, {message:'successed'});
            conn.end();
        });
    }).on('error', function(e){
        console.log(e);
        callback(1,{message:e.message});
    });
};
//--------------------------------------------------------
```
And the module: 'dnode' is from "http://github.com/substack/dnode.git"
It seems not recognize donde object correctly.

**Comment by jaredallard** [comment]
This seems to be tied in with a bunch of other odd bugs lately, I'm looking into it. However I have a very busy week and a half ahead of me (until Wednesday) so can't really do anything until then! Apologies!

**Comment by jaredallard** [comment]
Try the browserify branch, might fix it.

**Comment by jaredallard** [comment]
Any information on how this went?

**Comment by jaredallard** [comment]
browserify branch is now mainstream, try `nexe@1`. Closing until it's reported again!
