### ISSUE TITLE
Websocket Module Not getting Bundled

### ISSUE THREAD

**Issue by raghavezetap** [jaredallard/nexe#140]
Hello Guys,
I am getting issue with Websocket module and the exception is :- 

 TypeError: WebSocketServer is not a function
    at Array.__dirname.call.C:\Users\Raghav Tandon\WinPos\BrowserIntegrat
ion\js\Impl.js.http (nexe.js:15318:12)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call.C:\Users\Raghav Tandon\WinPos\BrowserIntegrat
ion\js\RestWS.js../RestImpl (nexe.js:48:20)
    at initModule (nexe.js:29:11)
    at Array.forEach (native)
    at nexe.js:39:8
    at nexe.js:46:4
    at NativeModule.compile (node.js:945:5)
    at Function.NativeModule.require (node.js:893:18)

Can you please help in figuring out why Websocket module is not loaded into the .exe file.

**Comment by jaredallard** [comment]
Reproducable code and more information please!

**Comment by jaredallard** [comment]
Closing due to inactivity, please respond!
