### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by goliatone** [jaredallard/nexe#152]
Running nexe on mac os 10.10.5, node 0.12.4:

```
$ nexe 
```

```
----> input => './bin/domon'
----> output => 'domon'
----> temp => '.src'
----> runtime.framework => 'node'
----> runtime.version => '0.12.4'
----> runtime.ignoreFlags => 'true'
----> framework => node
----> downloading https://node.org/dist/v0.12.4/node-v0.12.4.tar.gz
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

`package.json` nexe portion:

```json
"nexe": {
    "input": "./bin/amon",
    "output": "amon^$",
    "temp": ".src",
    "runtime": {
      "framework": "node",
        "version": "0.12.4",
        "ignoreFlags": true
    }
  }
```

**Comment by droninn** [comment]
Try chaningthe framework to nodejs instead of node.

**Comment by jaredallard** [comment]
Closing. Fix is to use nodejs as framework. Will correct node to nodejs
