### ISSUE TITLE
Not working with rc

### ISSUE THREAD

**Issue by issacg** [jaredallard/nexe#158]
I'm getting a reproducable error with rc (1.1.5)
```
nexe.js:72
    throw new Error('rc(name): name *must* be string')
    ^

Error: rc(name): name *must* be string
    at Object.module.exports (nexe.js:72:11)
    at Array.__dirname.call./home/user/v/node_modules/rc/index.js.path (nexe.js:117:27)
    at initModule (nexe.js:31:11)
    at nexe.js:33:64
    at Array.__dirname.call./home/user/v/test.js.rc (nexe.js:49:10)
    at initModule (nexe.js:31:11)
    at Array.forEach (native)
    at nexe.js:41:8
    at nexe.js:48:4
    at NativeModule.compile (node.js:959:5)

```

To reproduce
test.js
```
var rc = require('rc');
var def = {
  foo: "bar"
};

var opts = rc("test", def);

console.log(opts.foo);
```

`node test.js` produces the correct output: `bar`

Tried building with both `nexe -i test.js -o test -r 0.12.9` and `nexe -i test.js -o test -r 4.2.4`

**Comment by issacg** [comment]
The problem seems to be with the fact that rc tries to detect if it's running directly:

```
if(!module.parent) {
  console.log(
    JSON.stringify(module.exports(process.argv[2]), false, 2)
  )
}
```

Manually removing this from the module in node_modules seems to work around this...
