### ISSUE TITLE
Error child process spawn ENOENT

### ISSUE THREAD

**Issue by tresdin** [jaredallard/nexe#166]
I got this error when I tried this command `nexe -i /home/project/app.js -o /home/project/app.nex`
```
----> bundle /home/project/app.js
----> Browserify finished
----> embedResources undefined
----> resource -> /home/project/tmp/nexe/nodejs/latest/node-v5.5.0/lib/nexeres.js
----> make
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn ./configure ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```
Did I do anything wrong?

**Comment by jaredallard** [comment]
See #167.
