### ISSUE TITLE
Could not run build output: No such native module jszip

### ISSUE THREAD

**Issue by kennethlynne** [jaredallard/nexe#169]
```bash
/the-output ; exit;          
➜  ~  /the-output ; exit;
node.js:932
      throw new Error('No such native module ' + id);
      ^

Error: No such native module jszip
    at NativeModule.require (node.js:932:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at make_xlsx (nexe.js:35287:55)
    at Object.__dirname.97../dist/cpexcel (nexe.js:45602:3)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.69.lodash.defaults (nexe.js:20802:12)
    at s (nexe.js:1:316)
    at nexe.js:1:367

[Process completed]
```

**Comment by kennethlynne** [comment]
I understand it might be some of my dependencies not working in this environment?

**Comment by kennethlynne** [comment]
```js
var req = require('restler-q');
var async = require('async');
var argv = require('yargs').argv;
var xlsx = require('node-xlsx');
var _ = require('lodash');
var inquirer = require('inquirer');
```

**Comment by jaredallard** [comment]
I'll check this out tonight!

On Wed, Jan 27, 2016 at 6:55 AM, Kenneth Lynne < notifications@github.com [notifications@github.com] > wrote:
I understand it might be some of my dependencies not working in this
environment?

—
Reply to this email directly or view it on GitHub
[https://github.com/jaredallard/nexe/issues/169#issuecomment-175666932] .[https://github.com/notifications/beacon/ACR9NYReqZAV8-ldacuxId8SXfysHevLks5peNHAgaJpZM4HNeT-.gif]

**Comment by jaredallard** [comment]
First off, are any of your modules native?

**Comment by jaredallard** [comment]
I can't seem to reproduce, any example code?

**Comment by jaredallard** [comment]
May be related to #173.

**Comment by kennethlynne** [comment]
I worked around it now by removing the node-xlsx module! :)

**Comment by pinodex** [comment]
I got the same "No such native module" error.

```
Error: No such native module ./transports/console
    at NativeModule.require (node.js:932:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.Console (nexe.js:66015:12)
    at new exports.Container (nexe.js:65162:29)
    at Object.__dirname.259../winston/common (nexe.js:64514:19)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.193.events (nexe.js:47217:15)
    at s (nexe.js:1:316)
```

Can't seem to know why. My dependencies are

```
"cheerio": "^0.19.0",
"colors": "^1.1.2",
"keypress": "^0.2.1",
"prompt": "^0.2.14",
"request": "^2.69.0"
```
