### ISSUE TITLE
TypeError: Cannot read property 'output' of undefined

### ISSUE THREAD

**Issue by codekraft-studio** [jaredallard/nexe#186]
Hi there, I just tried to use nexe and I get this error:

My steps:

1. Downloaded nexe (via npm)
2. nexe -o bella.exe (in the project folder)
3. Error

> Z:\private\node\catalogue>nexe -o bella.exe
C:\Users\Filippo\AppData\Roaming\npm\node_modules\nexe\lib\exe.js:950
                _package.nexe.output = _package.nexe.output.replace(/\^\$/, '.exe') // exe
                                                    ^
TypeError: Cannot read property 'output' of undefined
    at Object.exports.package (C:\Users\Filippo\AppData\Roaming\npm\node_modules\nexe\lib\exe.js:950:39)
    at Object.<anonymous> (C:\Users\Filippo\AppData\Roaming\npm\node_modules\nexe\bin\nexe:71:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

I attached the output for a easy debugging with the line numbers of the error.

Also, I tried to understand why the error shows up and I found out that the code tries to use a "nexe" property in my package.json file that doesn't exist and causes the error in the file: exe.js at line 952-

Should I add nexe attribute to package.json manually?
I should have done `npm install nexe --save` ? 

Many thanks.

**Comment by jaredallard** [comment]
Thanks for this, the package method is still sorta buggy. It relies on having "output" and "input" (if you are using it) Otherwise, by not specifying an input `-i myinput.js` it will try to use that format and fail as it most likely wasn't setup.

**Comment by codekraft-studio** [comment]
Hi, I just tried with linux (opensuse leap) to do with input and output and I get another error but this time I'm not sure is from your package, can you help me to debug it? 
I don't know what's wrong and I really want to use your git! :cake: 
(by the way I didn't try in windows yet)

```bash
ll myApp/
total 8
-rw-r--r-- 1 commonuser users 134 Feb 22 18:51 index.html
-rw-r--r-- 1 commonuser users  70 Feb 22 18:52 package.json

nexe -i ./myApp -o app.exe
module.js:340
    throw err;
    ^

Error: Cannot find module 'myApp/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.exports.package (/usr/lib/node_modules/nexe/lib/exe.js:945:14)
    at Object.<anonymous> (/usr/lib/node_modules/nexe/bin/nexe:71:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by codekraft-studio** [comment]
how can I create an executable from a entire project folder? 
pack all the application and not only the entry file

**Comment by jaredallard** [comment]
Browserify will determine deps, anything not in a `require` statement won't be included. This is by design, if you want to bundle other files, you must use `nexeres` (`require("nexeres")`) and it's respective inclusion process during build!

You can control all of this in your `package.json` to make the build process easier by only having to invoke `nexe` (also makes reproducing builds much much easier)
