### ISSUE TITLE
ReferenceError: finalContents is not defined

### ISSUE THREAD

**Issue by jeff-blaisdell** [jaredallard/nexe#200]
*OS:* OS X 10.11.3

When running a clean Nexe install with the "flags: true" flag, Nexe fails with the following:

```
----> framework => nodejs
----> downloading https://nodejs.org/dist/v4.2.3/node-v4.2.3.tar.gz
[====================================================================================================]
----> extracting the node source [native tar]
----> tar -xf /Users/jblaisdell/Git/cli-dev/tmp/nodejs/4.2.3/nodejs-4.2.3.tar.gz -C /Users/jblaisdell/Git/cli-dev/tmp/nodejs/4.2.3
----> bundle ./lib/index.js
----> executing browserify via API
----> embedResources undefined
----> resource -> /Users/jblaisdell/Git/cli-dev/tmp/nodejs/4.2.3/node-v4.2.3/lib/nexeres.js
----> monkey patch /Users/jblaisdell/Git/cli-dev/tmp/nodejs/4.2.3/node-v4.2.3/node.gyp
----> monkey patch /Users/jblaisdell/Git/cli-dev/tmp/nodejs/4.2.3/node-v4.2.3/src/node.js
----> using the after 0.12.5 method of ignoring flags.
----> patched node.cc
/Users/jblaisdell/Git/cli-dev/node_modules/nexe/lib/exe.js:773
  finalContents = lines.join('\n');
                ^

ReferenceError: finalContents is not defined
    at _monkeyPatchMainCc (/Users/jblaisdell/Git/cli-dev/node_modules/nexe/lib/exe.js:773:17)
    at monkeyPatchNodeCc (/Users/jblaisdell/Git/cli-dev/node_modules/nexe/lib/exe.js:181:9)
    at fn (/Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:746:34)
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:1213:16
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:166:37
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:706:43
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:167:37
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:1209:30
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:52:16
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:1209:30
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:52:16
    at /Users/jblaisdell/Git/cli-dev/node_modules/nexe/node_modules/async/lib/async.js:1209:30
    at /Users/jblaisdell/Git/cli-dev/node_modules/cli-gulp-tools/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/jblaisdell/Git/cli-dev/node_modules/cli-gulp-tools/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/jblaisdell/Git/cli-dev/node_modules/cli-gulp-tools/node_modules/gulp-sourcemaps/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/jblaisdell/Git/cli-dev/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
```

**Comment by jeff-blaisdell** [comment]
Went to make the fix, but looks like you guys have already patched it in master.  Tried using master, but ran into new errors - so just patched the 1.1.0 fork I'm on.  If this impacts anyone else, can pull my tag until a new Nexe version is released.

```
"nexe": "git@github.com:jeff-blaisdell/nexe.git#1.1.0-flags"
```
